### ISSUE TITLE
Testing Action broken

### ISSUE THREAD

**Issue by Steve2955** [Steve2955/md2anki#40]
@RvNovae @ZeroPointMax Any Ideas on what to do about this?

![image](https://user-images.githubusercontent.com/21085384/158403039-65e8a81f-43a6-46da-882e-131e407c1eb0.png)

**Comment by nukerxy** [comment]
repo ist private aber das secret token darf nicht auf private zugreifen? dunno

**Comment by emkZero** [comment]
So let's sum up what happens here. Surely, devil's in the detail.

- ``npm ci`` triggers a reading git operation (ls-remote)
- it uses SSH for encryption
- it tries to access GitHub via 192.30.255.113
  - 192.0.0.0/8 is a private address range
  - therefore, it runs somewhere inside GH's network?
- the action can reach an SSH server under the given address, but GitHub refuses access, since it does not recognise its public key

Have i understood that corrrectly?
If so:

- where does the keypair even come from?
- how did it used to work anyways?
- are there any git write operations involved in ``npm ci`` or ``npm test``?
  - if not, is it possible to use HTTPS instead?

**Comment by emkZero** [comment]
Unfortunately, the old logs where it was still working are deleted already.

**Comment by Steve2955** [comment]
@ZeroPointMax The repo causing the issue is [Steve2955/anki-apkg-export](https://github.com/Steve2955/anki-apkg-export). It's installed using `npm` but through `git` -> see `package.json`:

![image](https://user-images.githubusercontent.com/21085384/158435777-a61f5098-e560-446b-8f3e-b25a9fd802f7.png)

The repo is public and installing `md2apkg` works fine locally and and using the actions in our orga. Which would require `anki-apkg-export` as well. That's why I don't understand, that it's causing issues here.

> Have i understood that corrrectly?

It seems like that reading the log, but the `package.json` tells a different story. Howevery redirecting between the different protocols shouldn't be that easy 🤔

**Comment by RvNovae** [comment]
This could be of interest: https://github.blog/changelog/2022-03-15-removed-unencrypted-git-protocol-and-certain-ssh-keys/

The timing would be very fitting as well.

**Comment by Steve2955** [comment]
> This could be of interest: https://github.blog/changelog/2022-03-15-removed-unencrypted-git-protocol-and-certain-ssh-keys/
> 
> The timing would be very fitting as well.

Oh no, that could be the cause. I should probably publish [`Steve2955/anki-apkg-export`](https://github.com/Steve2955/anki-apkg-export) on `npm` as well than 🤔

**Comment by RvNovae** [comment]
> Oh no, that could be the cause. I should probably publish [`Steve2955/anki-apkg-export`](https://github.com/Steve2955/anki-apkg-export) on `npm` as well than 🤔

Either that or switching to a different method of cloning the repo (I think).
Publishing it on `npm` is probably easier though.

**Comment by Steve2955** [comment]
[Successfully moved to `npm`](https://github.com/Steve2955/md2apkg/commit/e0affa407dbaa1b81b5323cec4399ff45c5721a1)

@RvNovae @ZeroPointMax @nukerxy Thank you everyone!
